[workspace]
resolver = "2"
members = [
    "forc",
    "forc-pkg",
    "forc-plugins/forc-client",
    "forc-plugins/forc-crypto",
    "forc-plugins/forc-doc",
    "forc-plugins/forc-fmt",
    "forc-plugins/forc-lsp",
    "forc-plugins/forc-tx",
    "forc-test",
    "forc-tracing",
    "forc-util",
    "scripts/mdbook-forc-documenter",
    "sway-ast",
    "sway-core",
    "sway-error",
    "sway-ir",
    "sway-ir/sway-ir-macros",
    "sway-lsp",
    "sway-parse",
    "sway-types",
    "sway-utils",
    "swayfmt",
    "test",
]
exclude = ["examples/*", "forc-test/test_data", "swayfmt/test_macros"]

[workspace.dependencies]
# Dependencies from the `fuel-core` repository:
fuel-core-client = { version = "0.20.3", default-features = false }

# Dependencies from the `fuel-vm` repository:
fuel-core-keygen = "0.20.8"
fuel-asm = "0.35.3"
fuel-crypto = "0.35.3"
fuel-types = "0.35.3"
fuel-tx = "0.35.3"
fuel-vm = "0.35.3"

# Dependencies from the `fuels-rs` repository:
fuels-core = "0.49"
fuels-accounts = "0.49"

# Dependencies from the `forc-wallet` repository:
forc-wallet = "0.3.0"

[workspace.package]
edition = "2021"
authors = ["Fuel Labs <contact@fuel.sh>"]
homepage = "https://fuel.network/"
license = "Apache-2.0"
repository = "https://github.com/FuelLabs/sway"

[patch.crates-io]
# Keep it until release of the `fuel-core`.
fuel-core-keygen = { git = "https://github.com/FuelLabs/fuel-core", branch = "master" }
fuel-core-client = { git = "https://github.com/FuelLabs/fuel-core", branch = "master" }
fuel-crypto = { git = "https://github.com/FuelLabs/fuel-vm", branch = "master" }

# Keep it until release of the `fuels-rs`.
fuels-core = { git = "https://github.com/FuelLabs/fuels-rs", branch = "upgrade/fuel-core-master" }
fuels-accounts = { git = "https://github.com/FuelLabs/fuels-rs", branch = "upgrade/fuel-core-master" }

# Keep it until release of the `forc-wallet`.
forc-wallet = { git = "https://github.com/FuelLabs/forc-wallet", branch = "upgrade/fuel-core-master" }
fuels = { git = "https://github.com/FuelLabs/fuels-rs", branch = "upgrade/fuel-core-master" }
